name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Print Environment Variables (for Debugging)
        run: env

      - name: Build Project
        run: npm install && npm run build # Modify based on your build process

      - name: Deploy to Cloudflare Pages
        run: |
          wrangler pages deploy dist/resume.md --project-name=resume-md --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
